commands:
  # Time
  - command:
    input: time
    entity: time
    action: getTime
  # Date
  - command:
    input: date
    entity: time
    action: getDate
  - command:
    input: day
    entity: time
    action: getDate
  - command:
    input: year
    entity: time
    action: getDate
  - command:
    input: month
    entity: time
    action: getDate
  - command:
    input: today
    entity: time
    action: getDate
  # Weather
  - command:
    input: weather
    entity: time
    action: getWeather
  # Open
  - command:
    input: open google
    entity: open
    action: google
  